server:
  port: 5001
spring:
  security:
    user:
      name: root
      password: s3cr3t
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://postgres:5432/patientdb
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
eureka:
  client:
    serviceUrl:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka-server:8761/eureka/
logging:
  level:
    org:
      springframework: INFO