eureka:
  client:
    serviceUrl:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka-server:8761/eureka/
spring:
  security:
    user:
      name: root
      password: s3cr3t
medilabo:
  api:
    url: http://gateway:8080/
risk:
  terms:
    - "Hémoglobine A1C"
    - "Microalbumine"
    - "Taille"
    - "Poids"
    - "Fumeur"
    - "Fumeuse"
    - "Anormal"
    - "Cholestérol"
    - "Vertiges"
    - "Rechute"
    - "Réaction"
    - "Anticorps"
server:
  port: 6001
management:
  endpoints:
    web:
      exposure:
        include: refresh